### ISSUE TITLE
Oracle Disputes

### ISSUE THREAD

**Issue by dsshap** [antoncoding/grappa#123]
Do we want to give some buffer for disputing an oracles price?

**Comment by antoncoding** [comment]
I will not want an oracle dispute, just so we can minimize centralization risks. I would prefer a "backup mechanism" to push the price if the current implementation failed to push price for a specific timestamp.

**Comment by dsshap** [comment]
I am more concerned about the oracle pushing the wrong price at expiry.

That risk falls to either the sell or the buy side depending on where the price lands. If there is window to dispute this than one side can take advantage of the discrepancy.

**Comment by antoncoding** [comment]
I think it's kind of hard to define what's a "wrong price" from smart contract's perspective. Considering that the on-chain world takes what oracle said as ground truth, I'd actually prefer we completely trust the oracle and state clearly that it will be used to settle all options.

I feel like adding dispute is another attack surface. Using chainlink as example, having a dispute mechanism means we trust our own disputer key more than Chainlink's "decentralized nodes", which I think is not fair

**Comment by dsshap** [comment]
In a perfect world i would agree with you. But these oracles are not that mature. If you recall there have been major errors with other major oracles (pyth). The errors they had would cause someone to lose significant funds.

If you structure the dispute role correctly (example:  multisig [signer to be determined]) then I think that gives participants some assurance that if things go wrong (which they eventually do) there is something that can be done about it.

**Comment by antoncoding** [comment]
I personally would consider separating these into different oracles, like a fully permission-less oracle rely 100% on chainlink, and another one with chainlink + disputable by admins.

Reason is, I think once we have a single component that inherit the centralisation risk, even the fully collateralised engine will become "not decentralized", because admin would be so powerful that they can change the payout of the system. Then we go back to the problem of "should we assume the admin to be good", and eventually the whole assumption go back to "trusting the key owners".

The good things about the current design is we can rely on different oracles, so we can do both and let the integrating team decide which one to go with.

**Comment by antoncoding** [comment]
I do feel like a "better" oracle could be something that 
* has a fullback to avoid single point of failure
* compared prices across different oracles (chainlink, pyth and uniswap maybe) while reporting
* only give small rooms to disputers (e.g. disputer can't change price 1% different than reported)

These would all be something needed before I consider it "decentralized"
